**Цель работы:**

Осуществить предварительную обработку данных csv-файла, выявить и устранить проблемы в этих данных.

# Загрузка набора данных

### Описание предметной области

Вариант №5

Набор данных: visits.csv

Атрибуты:
  1. user_id – идентификатор пользователя, тип данных int64;
  2. region – регион пользователя, тип данных object;
  3. region – регион пользователя, тип данных object;
  4. device – тип устройства, тип данных object;
  5. channel – рекламный канал, тип данных object;
  6. session_start – дата и время начала сессии, исходный тип данных object;
  7. session_end – дата и время окончания сессии, исходный тип данных object;
  8. time_session – продолжительность сессии в секундах, тип данных int64;
  9. click_count – количество кликов, тип данных int64;
  10. buy_count – количество покупок, тип данных int64;
  11. price – стоимость, тип данных float64;
  12. age – возраст пользователя, тип данных int64.

### 1.Чтение файла (набора данных)

In [36]:
# импорт библиотек, чтение файла с помощью pandas
import pandas as pd
df = pd.read_csv('visits.csv', sep=';')

### 2. Обзор данных

2.1 Вывод первых 20 строк с помощью метода head.

In [37]:
# применить метод head
df.head(20)

,user_id,region,device,channel,session_start,session_end,time_session,click_count,buy_count,price,age
0,278965908054,United States,iPhone,organic,01.05.2019 4:46,01.05.2019 4:47,1.0,0.0,0.0,0.0,31
1,244878945432,United States,Mac,organic,01.05.2019 16:44,01.05.2019 16:45,1.0,0.0,0.0,0.0,40
2,590706206550,United States,Mac,organic,01.05.2019 14:09,01.05.2019 15:32,83.0,28.0,6.0,14570.0,50
3,326433527971,United States,Android,TipTop,01.05.2019 0:29,01.05.2019 0:54,25.0,8.0,3.0,4411.0,38
4,349773784594,United States,Mac,organic,01.05.2019 3:33,01.05.2019 3:57,24.0,8.0,3.0,4411.0,63
5,90242400005,United States,Android,organic,01.05.2019 9:03,01.05.2019 10:08,65.0,22.0,4.0,11310.0,62
6,43958116050,United States,iPhone,organic,01.05.2019 9:37,01.05.2019 10:00,23.0,8.0,3.0,4411.0,60
7,15174034813,United States,Mac,organic,01.05.2019 13:33,01.05.2019 13:35,2.0,0.0,0.0,0.0,12
8,446013509831,United States,iPhone,organic,01.05.2019 14:44,01.05.2019 15:41,57.0,19.0,4.0,9872.0,52
9,100970711362,United States,Mac,FaceBoom,01.05.2019 6:20,01.05.2019 6:54,34.0,12.0,3.0,6326.0,25
10,23110169785,United States,iPhone,organic,01.05.2019 11:29,01.05.2019 11:31,2.0,0.0,0.0,0.0,27
11,370455852550,United States,iPhone,MediaTornado,01.05.2019 14:01,01.05.2019 14:29,28.0,10.0,3.0,5369.0,27
12,784885401335,Russia,iPhone,TipTop,01.05.2019 22:40,01.05.2019 22:41,1.0,0.0,0.0,0.0,31
13,619068889591,Russia,PC,FaceBoom,01.05.2019 20:14,01.05.2019 20:16,2.0,0.0,0.0,0.0,21
14,774938424092,Russia,Mac,organic,01.05.2019 17:06,01.05.2019 18:05,59.0,20.0,4.0,10352.0,28
15,762505039443,Russia,Android,organic,01.05.2019 23:30,01.05.2019 23:30,0.0,0.0,0.0,0.0,36
16,355761474010,Russia,iPhone,FaceBoom,01.05.2019 11:03,01.05.2019 11:05,2.0,0.0,0.0,0.0,30
17,221611265998,Russia,iPhone,organic,01.05.2019 0:19,01.05.2019 0:20,1.0,0.0,0.0,0.0,65
18,57218022811,Russia,iPhone,organic,01.05.2019 15:13,01.05.2019 15:15,2.0,0.0,0.0,0.0,53
19,88533696308,Russia,iPhone,organic,01.05.2019 12:26,01.05.2019 12:28,2.0,0.0,0.0,0.0,61

2.2 Оценка данных с помощью метода info.

In [38]:
# выполнит метод info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 954 entries, 0 to 953
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   user_id        954 non-null    int64
 1   region         953 non-null    str
 2   device         953 non-null    str
 3   channel        954 non-null    str
 4   session_start  954 non-null    str
 5   session_end    954 non-null    str
 6   time_session   954 non-null    float64
 7   click_count    954 non-null    float64
 8   buy_count      954 non-null    float64
 9   price          954 non-null    float64
 10  age            954 non-null    int64
dtypes: float64(4), int64(2), str(5)
memory usage: 82.1 KB

Набор данных содержит 11 столбцов и 954 записи итого. В стобцах region и device можно заметить по пропущенному значению.
В наборе данных используются следующие типы данных: int64 – для столбцов user_id и age, float64 – для time_session, click_count, buy_count и price и object – для region, device, channel, session_start и session_end

2.3 Оценка данных с помощью метода describe.

In [39]:
# оцените числовые столбцы с помощью describe
df.describe()

,user_id,time_session,click_count,buy_count,price,age
count,9.540000e+02,954.000000,954.000000,954.000000,954.000000,954.000000
mean,4.951807e+11,29.062893,9.830189,2.527254,5341.559748,39.810273
std,2.899488e+11,27.134816,9.209039,1.602003,5060.247685,13.038029
min,2.346325e+09,0.000000,0.000000,0.000000,0.000000,10.000000
25%,2.295122e+11,9.000000,3.000000,2.000000,2301.000000,29.000000
50%,4.984267e+11,21.000000,7.000000,2.000000,3739.000000,39.000000
75%,7.525332e+11,42.000000,14.000000,3.000000,7284.000000,50.000000
max,9.985130e+11,262.000000,88.000000,15.000000,56546.000000,71.000000

Describe позволяет посмотреть статистические характеристики числовых признаков набора данных, такие как количество значений, среднее арифметическое, стандартное отклонение, минимальное и максимальное значения, первый и третий квартили, и медиану.

Столбец user_id является идентификатором пользователя, поэтому для него все средние значения, не имеют смысла.

Средняя продолжительность пользовательской сессии составляет 29 минут, медианное значение - 21 минута. Минимальная продолжительность сессии равна 0, максимальная - 262 минуты. Значительное превышение максимального значения над средним может указывать на наличие отдельных продолжительных сессий. Минимальная сессия в 0.00 может свидетельствовать о неверной записи.

Среднее количество кликов за сессию составляет 9.83, медианное значение - 7. Минимальное количество кликов равно 0, максимальное - 88.

Среднее количество покупок составляет 2.53, медианное значение - 2. Минимальное количество покупок равно 0, максимальное - 15.

Средняя стоимость составляет 5341.56, медианное значение - 3739. Минимальное значение стоимости равно 0, максимальное - 56546. Большая разница между средним, медианой и максимальным значением свидетельствует о наличии отдельных записей с высокой стоимостью.

Средний возраст пользователей составляет 39.81 года, медианный возраст - 39 лет. Минимальный возраст равен 10 годам, максимальный - 71 году.

 2.4 Оценка названий столбцов

In [40]:
# Вывести на экран названия столбцов с помощью df.columns. Выявить проблемы с названиями, если они есть. При необходимости переименовать столбцы. Если проблемы не обнаружены также дать пояснения.
df.columns

Index(['user_id ', 'region', 'device', 'channel', 'session_start',
       'session_end', 'time_session', 'click_count', 'buy_count', 'price',
       'age'],
      dtype='str')

в столбце user_id в конце есть лишний пробел. для того чтобы от него избавиться необходимо использовать strip()

In [41]:
# переименование при необходимости
df.columns = df.columns.str.strip()
df.columns

Index(['user_id', 'region', 'device', 'channel', 'session_start',
       'session_end', 'time_session', 'click_count', 'buy_count', 'price',
       'age'],
      dtype='str')

### 3. Проверка пропусков

In [42]:
# Проверить данные на наличие пропусков и устранить их, если они есть (пропуски необходимо либо удалить, либо заменить каким-то значением).

как было замечено ранее в столбцах region и device есть по пропуску, необходимо обработать пропуски в этих записях.

In [43]:
df = df.dropna()
df.isna().sum()

user_id          0
region           0
device           0
channel          0
session_start    0
session_end      0
time_session     0
click_count      0
buy_count        0
price            0
age              0
dtype: int64

Как можно заметить пропусков больше нет. Так как пропусков было всего два, а записей сильно больше было принято решение просто удалить записи вместо заполнения их средними данными, так как их отсутвие не сильно повлияет на общую картину.

### 4. Проверка дубликатов

#### Проверка явных дубликатов

In [44]:
df.duplicated().sum()

np.int64(0)

Явные дупликаты отсутствуют

#### Проверка неявных дубликатов

In [45]:
print('region:', df['region'].unique())
print('device:', df['device'].unique())
print('channel:', df['channel'].unique())

region: <StringArray>
['United States', 'Russia', 'USA']
Length: 3, dtype: str
device: <StringArray>
['iPhone', 'Mac', 'Android', 'PC', 'MAC', 'IPHONE']
Length: 6, dtype: str
channel: <StringArray>
['organic', 'TipTop', 'FaceBoom', 'MediaTornado']
Length: 4, dtype: str

после проверки можно заметить что явно одинаковые вещи разными пользователями могут быть записаны по разному, например: 'United States' и 'USA', 'Mac' и 'MAC', 'iPhone' и 'IPHONE'. Поэтому необходимо привести эти значения к единому виду и провести провекру на дубликаты ещё раз.

In [46]:
df['region'] = df['region'].replace('United States', 'USA')
df['device'] = df['device'].replace({
    'MAC': 'Mac',
    'IPHONE': 'iPhone'
})

print('region:', df['region'].unique())
print('device:', df['device'].unique())

region: <StringArray>
['USA', 'Russia']
Length: 2, dtype: str
device: <StringArray>
['iPhone', 'Mac', 'Android', 'PC']
Length: 4, dtype: str

Теперь неоднозначных значений нет

In [47]:
df.duplicated().sum()

np.int64(0)

После приведения неоднознеачных значений к единому виду явных дубликатов не появилось

### 5. Провека типов данных

In [48]:
print((df['click_count'] % 1 == 0).all())
print((df['buy_count'] % 1 == 0).all())
print((df['time_session'] % 1 == 0).all())

True
True
True

In [49]:
#Три столбца с форматом данных float64, но в них по логике должны быть только целые числа. После проверки видно что числа действительно целыее, так что преобразуем их в формат int64.
df['click_count'] = df['click_count'].astype('int64')
df['buy_count'] = df['buy_count'].astype('int64')
df['time_session'] = df['time_session'].astype('int64')

Столбцы session_start и session_end содержат дату и время, поэтому их надо преобразовать из типа object в datetime.
Остальные столбцы находятся в подходящих им форматах.

In [50]:
df['session_start'] = pd.to_datetime(df['session_start'])
df['session_end'] = pd.to_datetime(df['session_end'])

In [51]:
df.dtypes

user_id                   int64
region                      str
device                      str
channel                     str
session_start    datetime64[us]
session_end      datetime64[us]
time_session              int64
click_count               int64
buy_count                 int64
price                   float64
age                       int64
dtype: object

### 6. Группировка данных

#### Задание 1

*`Группировка - device и количество рекламных источников каждого типа (channel)`*

In [52]:
# выполните группировку согласно варианту
df.groupby(['device', 'channel']).size()

device   channel
Android  FaceBoom         33
         MediaTornado     11
         TipTop           26
         organic         115
Mac      FaceBoom         36
         MediaTornado     10
         TipTop           24
         organic         174
PC       FaceBoom         15
         MediaTornado      2
         TipTop           14
         organic          72
iPhone   FaceBoom         65
         MediaTornado     28
         TipTop           78
         organic         249
dtype: int64

По результатам группировки видно, что для всех типов устройств наибольшее количество записей приходится на рекламный канал organic. Наименьшее количество записей - на канал MediaTornado. Среди устройств наибольшее общее количество записей связано с iPhone, наименьшее - с PC.

#### Задание 2

*`Группировка - region и количество устройств (device). Создать датафрейм. Переименовать столбец с количеством в “сount”. Отсортировать по убыванию столбца “count”.`*

In [53]:
# выполните группировку согласно варианту
ndf = df.groupby('region')['device'].count().reset_index()
ndf = ndf.rename(columns={'device': 'count'})
ndf.sort_values(by='count', ascending = False)

   region  count
1     USA    900
0  Russia     52

Видно что из США записей коллосально больше чем из России. Из работы выше можно постановить что все данные были отобраны - всего регионов действительно два, а в сумме они дают все 952 записи.

#### Задание 3

*`Сводная таблица (pivot_table) - уникальное количество пользователей для каждого устройства (device). Отсортировать по убыванию количества.`*

In [54]:
# выполните сводную таблицу согласно варианту
df3 = df.pivot_table(index='device', values='user_id', aggfunc='nunique')
df3.sort_values(by='user_id', ascending = False)

         user_id
device
iPhone       389
Mac          231
Android      178
PC           103

из результатов сводной таблицы видно количетсво пользователей для каждого устройства. Наибольшее число пользователей приходится на iPhone, наименьшее - на PC.

#### Задание 4

*`Сводная таблица (pivot_table) - уникальное количество пользователей для каждого устройства (device) - столбцы и регионастроки. Отсортировать по возрастанию столбца region.`*

In [55]:
# выполните сводную таблицу согласно варианту
df4 = df.pivot_table(index='region', columns='device', values='user_id', aggfunc='nunique')
df4.sort_index(ascending=True)

device  Android  Mac  PC  iPhone
region
Russia       11   12   6      23
USA         167  220  97     368

Из результатов сводной таблицы видно, что в обоих регионах наибольшее количество пользователей приходится на iPhone. В России iPhone используют 23 пользователя, Mac - 12, PC - 6, Android - 11. В США количество пользователей значительно выше, что подтверждает результаты задания 2: iPhone - 368, Mac - 220, PC - 97, Android - 167. Таким образом, iPhone является самым распространённым устройством среди пользователей в обоих регионах, а PC - наименее распространённым.

### Вывод


В рамках этой лабораторной работы я исследовал датасет `visits.csv`, в котором собраны данные о визитах на сайт пользователей (их ID, возраст, страна, устройство, источник рекламы, время и длительность сессий, число кликов, покупок и их стоимость).

Сначала я проверил структуру таблиц через `info()` и `describe()`. Всего в базе оказалось 954 строки, две из которых были впоследствии удалены из-за ошибок их заполнения, и 11 столбцов. В столбцах с регионами и устройствами были пропуски - так как их было мало, я просто удалил эти строчки. Полных дубликатов в данных не нашлось, но всплыли неявные повторы из-за разного регистра и написания: USA / United States, MAC / Mac и IPHONE / iPhone. Я привел их к общему стандарту, а также убрал лишний пробел в имени колонки user_id. Кроме того, я поправил типы данных: даты и время перевел в datetime, а клики, покупки и время сессии сделал целыми числами (`int64`).

Также были выполнены задания - я сгруппировал данные и сделал несколько сводных таблиц, чтобы найти закономерности:
  - По рекламе и устройствам: на всех гаджетах самым популярным источником оказался organic (больше всего у владельцев iPhone - 249 записей). А вот канал MediaTornado, наоборот, приносил меньше всего трафика почти везде.
  - По странам: огромная часть сессий (900 штук) пришлась на США, и только 52 - на Россию.
  - По популярности устройств: чаще всего сервисом пользуются с iPhone (389 уникальных пользователей), на втором месте Mac (231), дальше идут Android (178) и PC (103). Такое распределение популярности устройств идентично для обоих регионов.

В итоге я полностью очистил массив данных от ошибок и подготовил его к работе, а также наглядно увидел, как именно распределяется аудитория по странам, своим устройствам и рекламным источникам.

### Дополнительное задание

**`Подробная формулировка задания`**

In [56]:
# код выполнения задания

***`Подробный вывод по заданию, описание полученных результатов`***